package com.anonos.bigprivacy.starter;

import com.anonos.bigprivacy.privacypolicyapi.DataType;
import com.anonos.bigprivacy.privacypolicyapi.Field;
import com.anonos.bigprivacy.privacypolicyapi.RuleExecutionException;
import com.anonos.bigprivacy.privacypolicyapi.PrivacyPolicy;
import com.anonos.bigprivacy.privacypolicyapi.PrivacyPolicyRule;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * A sample policy that doesn't do much.
 */
public class StarterPolicy implements PrivacyPolicy {

    public String getId() {
        // TODO Return a unique ID.  You may want to use a V4 UUID, which may
        // TODO be generated here: <https://www.uuidgenerator.net/>
        return null;
    }

    public String getName() {
        // TODO Return the name of this policy.  It should be a short string.
        return null;
    }

    public String getDescription() {
        // TODO Return a long but concise description of this policy.
        return null;
    }

    public Set<DataType> getInputTypes() {
        // TODO Return a list of data types accepted by this policy.  Most
        // TODO of the time, this will just be "TEXT", which is already
        // TODO set up below.
        final Set<DataType> dataTypes = new HashSet<DataType>();
        dataTypes.add(DataType.TEXT);
        return dataTypes;
    }

    public List<PrivacyPolicyRule> getRules() {
        // TODO Return a list of instantiated rules for this policy.  You may
        // TODO want to store rule objects in a class member Set or List for
        // TODO easy retrieval.
        return null;
    }

    /**
     * A sample rule.
     */
    private static class StarterRule implements PrivacyPolicyRule {
        public String getName() {
            // TODO Return the name of this rule.  It should be a short string.
            // TODO This name will be inserted into the name of the new field
            // TODO that is generated by this rule, so keep the name concise.
            return null;
        }

        public String getResult(final Object input, final List<Field> fields, final List<Object> row) throws RuleExecutionException {
            // TODO Perform the rule computation on the input value and return the result.  This
            // TODO rule may examine the entire record that is undergoing transformation by
            // TODO reading the "fields" and "row" parameters.  Any errors that occur during
            // TODO rule execution should cause a RuleExecutionException to be thrown.  Note
            // TODO that null is an acceptable value to return from this method, but it should
            // TODO generally only be used if the input is also null.
            return null;
        }
    }
}
